In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/basilb2s/language-detection/Language Detection.csv


In [2]:
import pandas as pd
import numpy as np

df= pd.read_csv(r"/kaggle/input/datasets/basilb2s/language-detection/Language Detection.csv")

In [3]:
df.shape

(10337, 2)

In [4]:
df.columns

Index(['Text', 'Language'], dtype='object')

In [5]:
def clean_text(text: str):
    text = text.lower()
    text =text.strip()
    return text
    
    

In [6]:
df['cleaned_text']=df['Text'].apply(clean_text)

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

cvectorize= CountVectorizer(analyzer='char',ngram_range=(2,5),max_features=3000,min_df=1)
X=cvectorize.fit_transform(df['cleaned_text'])


In [8]:
tfvector=TfidfVectorizer(analyzer='char',ngram_range=(2,5),max_features=3000,min_df=1)
X=tfvector.fit_transform(df['cleaned_text'])

In [9]:
Y=df['Language']

In [10]:
from sklearn.model_selection import train_test_split
X_Train,X_test,y_Train,y_Test=train_test_split(X,Y,test_size=0.15,random_state=42,stratify=Y)

In [11]:
from sklearn.linear_model import LogisticRegression
Lr_model=LogisticRegression(max_iter=5000,C=0.5,class_weight="balanced",random_state=42)


In [12]:
Lr_model.fit(X_Train,y_Train)



LogisticRegression(C=0.5, class_weight='balanced', max_iter=5000,
                   random_state=42)

In [13]:
y_pred=Lr_model.predict(X_test)
y_pred

array(['German', 'Arabic', 'Spanish', ..., 'French', 'French', 'Spanish'],
      dtype=object)

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

Lr_model.score(X_test,y_Test)

0.9800128949065119

In [15]:
accuracy_score(y_Test,y_pred)

0.9800128949065119

In [16]:
print(confusion_matrix(y_Test,y_pred))

[[ 80   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  62   0   0   0   1   0   0   0   0   0   0   0   0   0   0   1]
 [  0   0  79   0   0   2   0   0   0   0   0   0   0   0   1   0   0]
 [  0   1   0 205   0   0   0   0   2   0   0   0   0   0   0   0   0]
 [  0   0   0   1 148   0   0   0   1   0   0   1   0   0   0   0   1]
 [  0   0   0   0   0  71   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0  55   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0  10   0   0   0   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   0 102   0   0   1   0   1   0   0   0]
 [  0   0   0   0   0   0   0   0   0  53   0   0   0   0   0   0   2]
 [  0   0   0   0   0   0   0   0   0   0  89   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   1   0   0 106   0   2   0   0   2]
 [  0   0   0   0   1   0   0   0   0   0   0   0 102   0   0   0   1]
 [  0   0   0   1   0   0   0   0   1   0   0   0   0 121   0   0   0]
 [  0 

In [17]:
print(classification_report(y_Test,y_pred))

              precision    recall  f1-score   support

      Arabic       1.00      1.00      1.00        80
      Danish       0.93      0.97      0.95        64
       Dutch       1.00      0.96      0.98        82
     English       0.98      0.99      0.98       208
      French       0.99      0.97      0.98       152
      German       0.96      1.00      0.98        71
       Greek       1.00      1.00      1.00        55
       Hindi       1.00      1.00      1.00        10
     Italian       0.95      0.97      0.96       105
     Kannada       1.00      0.96      0.98        55
   Malayalam       1.00      1.00      1.00        89
  Portugeese       0.98      0.95      0.97       111
     Russian       1.00      0.98      0.99       104
     Spanish       0.98      0.98      0.98       123
    Sweedish       0.99      0.96      0.97       101
       Tamil       1.00      1.00      1.00        70
     Turkish       0.91      0.99      0.95        71

    accuracy              

In [18]:
text="Olá, meu nome é Ravi"
cvText=cvectorize.transform([text])

print("Vectorized:",cvText.shape)
print("non-zero elements:", cvText.nnz)
y_pred=Lr_model.predict(cvText)
print(f" input text is '{text}' and predicted language is : {y_pred}")

Vectorized: (1, 3000)
non-zero elements: 25
 input text is 'Olá, meu nome é Ravi' and predicted language is : ['Portugeese']


In [19]:
print("Vectorized:",vecotor.shape)
print("non-zero elements:", vecotor.nnz)

NameError: name 'vecotor' is not defined

In [ ]:
import pickle

with open("/kaggle/working/Final_LR_model.pkl",'wb') as file :
    pickle.dump(Lr_model,file)



    

In [ ]:
with open("/kaggle/working/final_Vector.pkl",'wb') as file :
    pickle.dump(tfvector,file)

In [ ]:
df['Language'].value_counts()